// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

//go:build !windows

// Package ebpfperf wraps github.com/cilium/ebpf/perf so that shared Cilium
// code can compile on platforms where the upstream perf package is not built
// (it carries a //go:build !windows constraint). On supported platforms the
// wrapper aliases the upstream types and forwards the constructors so behavior
// is unchanged; on Windows a functional no-op reader is provided instead.
package ebpfperf

import (
	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/perf"
)

// Record is an alias for perf.Record.
type Record = perf.Record

// Reader is an alias for perf.Reader.
type Reader = perf.Reader

// ReaderOptions is an alias for perf.ReaderOptions.
type ReaderOptions = perf.ReaderOptions

// NewReader creates a new perf reader over the given PerfEventArray map.
func NewReader(array *ebpf.Map, perCPUBuffer int) (*Reader, error) {
	return perf.NewReader(array, perCPUBuffer)
}

// IsUnknownEvent reports whether err was generated by an unknown event.
func IsUnknownEvent(err error) bool {
	return perf.IsUnknownEvent(err)
}
